Added a feature to copy code, discussed in issue #5914
react-bootstrap/react-bootstrap pull request #5919
Opened 2021-07-11 15:39 UTC by VibhorJaiswal

![image](https://user-images.githubusercontent.com/69683278/125201312-30fb3380-e28c-11eb-8749-3ade0e364a2a.png)
![image](https://user-images.githubusercontent.com/69683278/125201317-39536e80-e28c-11eb-9d40-6ad6052887fa.png)
![image](https://user-images.githubusercontent.com/69683278/125201325-3fe1e600-e28c-11eb-9c9d-f33a6991023d.png)

2021-07-15 13:27 UTC, eirikb approved these changes
LGTM

2021-07-22 05:18 UTC, kyletsang requested changes

2021-07-22 13:18 UTC, VibhorJaiswal commented
1) react-bootstrap `Tooltip` does not scale according to its contents, so when the content inside the `Tooltip` changes it results like this 
![image](https://user-images.githubusercontent.com/69683278/126641737-2befcdbf-5007-4211-9730-023e1c45a239.png)

also using two different `Tooltips ` will decrease code readability significantly. Although I did use the react-bootstrap `Button`.

2) 

> It's better to declare this in a function like `handleBlur` for readability

Done ✅


3) 

> Haven't looked too deeply into react-live, but does the editor expose a way for you to set code as a value so we can use it as a controlled editor?

As far as I know there is a  `onChange` event but when using it, the `react-live` stops showing errors on erroneous code.
Also when I tested, it was working totally fine when using `onBlur` event(also when the code is changed).

2021-07-22 13:19 UTC, VibhorJaiswal commented on www/src/components/ReactPlayground.js
> +        onBlur={(e) => {handleBlur(), handleCodeChange(e)}}
1) react-bootstrap `Tooltip` does not scale according to its contents, so when the content inside the `Tooltip` changes it results like this 
![image](https://user-images.githubusercontent.com/69683278/126641737-2befcdbf-5007-4211-9730-023e1c45a239.png)

also using two different `Tooltips ` will decrease code readability significantly. Although I did use the react-bootstrap `Button`.

2) 

> It's better to declare this in a function like `handleBlur` for readability

Done ✅


3) 

> Haven't looked too deeply into react-live, but does the editor expose a way for you to set code as a value so we can use it as a controlled editor?

As far as I know there is a  `onChange` event but when using it, the `react-live` stops showing errors on erroneous code.
Also when I tested, it was working totally fine when using `onBlur` event(also when the code is changed).

2021-07-23 05:32 UTC, VibhorJaiswal commented
@kyletsang 
1) react-bootstrap `Tooltip` does not scale according to its contents, so when the content inside the `Tooltip` changes it results like this 
![image](https://user-images.githubusercontent.com/69683278/126641737-2befcdbf-5007-4211-9730-023e1c45a239.png)

also using two different `Tooltips ` will decrease code readability significantly. Although I did use the react-bootstrap `Button`.

2) 

> It's better to declare this in a function like `handleBlur` for readability

Done ✅


3) 

> Haven't looked too deeply into react-live, but does the editor expose a way for you to set code as a value so we can use it as a controlled editor?

As far as I know there is a  `onChange` event but when using it, the `react-live` stops showing errors on erroneous code.
Also when I tested, it was working totally fine when using `onBlur` event(also when the code is changed).

2021-07-23 23:52 UTC, kyletsang commented
> react-bootstrap `Tooltip` does not scale according to its contents, so when the content inside the `Tooltip` changes it results like this
>

Might be able to use this for the dynamic content:
https://react-bootstrap.github.io/components/overlays/#overlays-dynamic-updates

2021-07-24 07:59 UTC, VibhorJaiswal commented
@kyletsang 
1) > Can we use existing react-bootstrap components here (Button and Tooltip)? That way, you wouldn't have to define new styles for the button/tooltip. ✅

2) > It's better to declare this in a function like `handleBlur`for readability. ✅

2021-07-26 05:51 UTC, kyletsang reviewed
Looking good.  Couple more comments.  Can you also run prettier on the files you've changed?  I'm noticing there's some style inconsistencies.

2021-07-26 05:51 UTC, kyletsang commented on www/src/components/ReactPlayground.js
> +  const UpdatingPopover = React.forwardRef(
Components shouldn't be nested within another component.  This should be declared outside.

2021-07-26 05:51 UTC, kyletsang commented on www/src/components/ReactPlayground.js
> +                <Button onClick={handleCopy} className={styles.styledCopyButton} variant='dark' value={codeText} >
Is `value` needed here?

2021-07-27 10:56 UTC, VibhorJaiswal commented
@kyletsang 
> Can you also run prettier on the files you've changed? I'm noticing there's some style inconsistencies.

I have prettified according to my prettier, if this is not what you want then can you please help me in this case.

2021-08-08 07:24 UTC, SaltyBuckets commented
> Can you also run prettier on the files you've changed? 

@kyletsang  tbh you should add a bot to do that to decrease the load on new contributers

2021-08-11 06:19 UTC, kyletsang approved these changes

2021-08-11 06:20 UTC, kyletsang commented
I think this is a good first pass.  @jquense, want to review?

2021-09-14 15:18 UTC, merged

2021-09-14 15:19 UTC, kyletsang commented
Sorry for delay on this.  Thanks for PR!

2021-09-14 15:40 UTC, VibhorJaiswal commented
@kyletsang no problem - thanks