test(card): refactor card component test to typescript and eliminate enzyme
react-bootstrap/react-bootstrap pull request #6166
Opened 2022-01-02 18:39 UTC by jayeclark

Signed-off-by: Jay Clark <jay@jayeclark.dev>

Partially fixes #6156 

Opening a draft PR to check that I'm on the right path, but I'd happily add additional commits covering more tests. (I could use the practice! 🙂)

2022-01-03 06:34 UTC, kyletsang requested changes
Few comments, but everything else looks good!

2022-01-03 06:34 UTC, kyletsang commented on test/CardSpec.tsx
> +    const results = getAllByText('Card');
We can just do a `getByText` here and not worry about checking for multiples

2022-01-03 06:34 UTC, kyletsang commented on test/CardSpec.tsx
> +    getAllByTestId('default-test').length.should.equal(1)
We don't need the `getAllByTestId` line here

2022-01-03 21:54 UTC, jayeclark commented
Great, thanks! I took care of migrating Container, Col, and Row too.

2022-01-04 17:21 UTC, kyletsang approved these changes

2022-01-04 17:22 UTC, merged

2022-01-04 17:22 UTC, kyletsang commented
Thanks!